### PR TITLE
Prevent KeyManager from setting up services for a key on config change

### LINKED ISSUE #165: KeyManager increments ManagedServices.uses on config change
I noticed this while developing my own app, and can reproduce it in the TreeKey sample.

STR:
- Open sample app.
- Click to continue.
- Select Maggie Simpson.
- Change the name to Billy.
- Rotate the screen.
- Click save.
- Press back. Note: Maggie Simpson is changed to Billy.
- Press back to the welcome screen.
- Click to continue.

Expected: Maggie Simpson is at the bottom of the list. The ContactStorage is destroyed so the Contact data is reset.
Actual: Billy is at the bottom of the list. The KeyManager retained the Services for the ContactsUi Key because the ManagedServices.uses field never reached 0.

This appears to be happening because KeyManager#setUp(key) is called within flow.setDispatcher(dispatcher) in InternalLifecycleIntegration#onActivityCreated(). I don't believe  setUp(key) needs to be called again since the KeyManager instance is retained in  InternalLifecycleIntegration.

### PR DESCRIPTION
**Pull request by Kritarie**
Resolve #165

### CODE REVIEW

**Comment by loganj** [comment]
Nice catch, and thanks for fixing!

**Comment by zoopolitic** [comment]
@Kritarie @loganj This fix does not contained in 1.0.0-alpha?

**Comment by Kritarie** [comment]
@zoopolitic this was fixed after alpha release, so I assume it won't be in the published lib until later (beta?)

**Comment by zoopolitic** [comment]
@Kritarie sad to hear :( I've came to this issue because encountered similar behavior but not with configuration changes. When you open another activity, e.g. to pick image from gallery - after return to current activity Flow.setUp() performs uses++ in ensureNode(), this breaks tearDown logic, because if you open and close new activity 10 times - there will be +10 uses. So question is, does this commit fixes this problem too ?

**Comment by Kritarie** [comment]
@zoopolitic I didn't test against that case, but this commit should correct that issue as well.

**Pull request merged**
